### ISSUE TITLE
Invalid auth/bad request (got a 400, expected HTTP/1.1 20X or a redirect)

### ISSUE THREAD

**Issue by amitcorcrm** [intuit/QuickBooks-V3-PHP-SDK#56]
I am getting below error when we create a service type products using API call. This error comes when we call API first time and if I can call same API again then it will work fine. please tell me where I was wrong.
Please help me on this how can i resolve it.

```
`Invalid auth/bad request (got a 400, expected HTTP/1.1 20X or a redirect)Array
(
    [0] => 400
    [1] => <?xml version="1.0" encoding="UTF-8" standalone="yes"?><FaultInfo xmlns="http://www.intuit.com/sb/cdm/baseexceptionmodel/xsd"><Message>Bad Request</Message><ErrorCode>400</ErrorCode><Cause>CLIENT</Cause></FaultInfo>
    [2] => Array
        (
            [Server] => nginx
            [Content-Type] => application/xml
            [Content-Length] => 215
            [Connection] => close
            [Strict-Transport-Security] => max-age=15552000
            [intuit_tid] => a206578a-7d0d-d8d9-89ed-f6e36510c7c8
            [Vary] => Accept-Encoding
        )

)`
```

My Code is
$itemObj = new IPPItem();
	$itemObj->Name = 'discountAtCorcrm';
	$itemObj->PurchaseCost = 0;
	$itemObj->UnitPrice = 0;
	$itemObj->Taxable = 'false';
	$itemObj->SalesTaxIncluded = 'false';			
	$itemObj->Type = 'Service';
	$obj = new IPPReferenceType();
	$obj->value = $AccountId;			
	$itemObj->IncomeAccountRef = $obj;
	try{
		$resultingCustObj = $dataService->Add($itemObj);
		$quickbooks_pid = $resultingCustObj->Id;
				
	} catch (Exception $e){		
		$errors .= "\n".$name." product add exception:";
		$errors .= "Error Message:".$e->getMessage();
	}

**Comment by hlu2** [comment]
Hi @amitcorcrm 
based on the error message:
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog. at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198) at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177) at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400) at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1473) at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:998) at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504) at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:211)

It seems like the Body of xml is somehow malformed. Check the Request Log/Response Log, see if you have all the values you set. 

Hao

**Comment by hlu2** [comment]
@amitcorcrm 
I have update the SDK to handle all primitive type. It should give you the correct result now,
